# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inspection_tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.url_line = QtWidgets.QLineEdit(self.centralwidget)
        self.url_line.setGeometry(QtCore.QRect(50, 30, 250, 20))
        self.url_line.setObjectName("url_line")
        self.soapaction_line = QtWidgets.QLineEdit(self.centralwidget)
        self.soapaction_line.setGeometry(QtCore.QRect(380, 30, 120, 20))
        self.soapaction_line.setObjectName("soapaction_line")
        self.equid_line = QtWidgets.QLineEdit(self.centralwidget)
        self.equid_line.setGeometry(QtCore.QRect(50, 70, 100, 20))
        self.equid_line.setObjectName("equid_line")
        self.mfid_line = QtWidgets.QLineEdit(self.centralwidget)
        self.mfid_line.setGeometry(QtCore.QRect(200, 70, 300, 20))
        self.mfid_line.setObjectName("mfid_line")
        self.send_text = QtWidgets.QTextEdit(self.centralwidget)
        self.send_text.setGeometry(QtCore.QRect(50, 140, 450, 550))
        self.send_text.setObjectName("send_text")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(310, 710, 80, 30))
        self.reset_button.setObjectName("reset_button")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(420, 710, 80, 30))
        self.send_button.setObjectName("send_button")
        self.recive_text = QtWidgets.QTextEdit(self.centralwidget)
        self.recive_text.setGeometry(QtCore.QRect(570, 140, 450, 550))
        self.recive_text.setObjectName("recive_text")
        self.url_lable = QtWidgets.QLabel(self.centralwidget)
        self.url_lable.setGeometry(QtCore.QRect(15, 30, 20, 20))
        self.url_lable.setObjectName("url_lable")
        self.soapaction_lable = QtWidgets.QLabel(self.centralwidget)
        self.soapaction_lable.setGeometry(QtCore.QRect(310, 30, 70, 20))
        self.soapaction_lable.setObjectName("soapaction_lable")
        self.euqid_lable = QtWidgets.QLabel(self.centralwidget)
        self.euqid_lable.setGeometry(QtCore.QRect(10, 70, 30, 20))
        self.euqid_lable.setObjectName("euqid_lable")
        self.mfid_lable = QtWidgets.QLabel(self.centralwidget)
        self.mfid_lable.setGeometry(QtCore.QRect(165, 70, 30, 20))
        self.mfid_lable.setObjectName("mfid_lable")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.url_line.setToolTip(_translate("MainWindow", "<html><head/><body><p>URL</p></body></html>"))
        self.reset_button.setText(_translate("MainWindow", "重置"))
        self.send_button.setText(_translate("MainWindow", "发送"))
        self.url_lable.setText(_translate("MainWindow", "URL"))
        self.soapaction_lable.setText(_translate("MainWindow", "SoapAction"))
        self.euqid_lable.setText(_translate("MainWindow", "equid"))
        self.mfid_lable.setText(_translate("MainWindow", "mfid"))


