#数据库
DATABASE:
  db: auto_b_server

#可测试能力
FEATURE:
  featurelist: [ 'B_FScan', 'B_PScan', 'B_SglFreqMeas', 'B_SglFreqDF', 'B_WBDF', 'B_FScanDF' ]

#检查实时任务
CHECK:
  host: 192.168.11.74
  #任务执行时间(秒)
  executetime: 10

