# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChildrenForm2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildrenForm2(object):
    def setupUi(self, ChildrenForm2):
        ChildrenForm2.setObjectName("ChildrenForm2")
        ChildrenForm2.resize(652, 528)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ChildrenForm2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(ChildrenForm2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)

        self.retranslateUi(ChildrenForm2)
        QtCore.QMetaObject.connectSlotsByName(ChildrenForm2)

    def retranslateUi(self, ChildrenForm2):
        _translate = QtCore.QCoreApplication.translate
        ChildrenForm2.setWindowTitle(_translate("ChildrenForm2", "ChildrenForm2"))
        self.textEdit.setHtml(_translate("ChildrenForm2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">我是子窗口的内容</span></p></body></html>"))
