config:

  #基础信息
  areacode: 510100
  longitudemin: 102.875976
  longitudemax: 105.292968
  latitudemin: 29.640320
  latitudemax: 31.672083
  token: eyJjbGllbnRpZCI6IjlmNzU3ZGE5LWJlOGQtNGE2Mi05Mjc0LTQ5Y2RjYWFlYTIyMyIsInVzZXIiOiI0MzAwMDAwMSIsInBhc3N3b3JkIjoiMTIzNDU2IiwiY2l0eSI6Iua5luWNl+ecgSIsImFyZWFDb2RlIjoiNDMwMDAwIiwidXNlcnJtcG5vIjoiNDMwMDAwMDEiLCJ1c2VybmFtZSI6IuiHquWKqOWMliIsInN0YXR1cyI6ZmFsc2UsInByaW9yaXR5IjoxfQ==

  #用户信息
  currentuserid: 51000001
  currentusername: 成都无线电管理员

  #管控url信息
  facility_add: http://192.168.11.134:54000/facility/add
  equip_add: http://192.168.11.134:54000/device/add
  facility_list: http://192.168.11.134:54000/facility/list
  equip_list: http://192.168.11.134:54000/device/list
  function_add: http://192.168.11.134:54000/function/add

  #全景运维url信息
  machine_add: http://192.168.11.134:11220/machine
  machie_list: http://192.168.11.134:11220/machineRoom/search
  software_add: http://192.168.11.134:11220/software
  cluster_list: http://192.168.11.134:11220/cluster/search
  serversoftware_monitor: http://192.168.11.134:11220/serverSoftware
  software_list: http://192.168.11.134:11220/software/search
  machine_list: http://192.168.11.134:11220/machine/search
  mobile_add: http://192.168.11.134:8082/machineTrack

  #网络信息
  gateway_ip: 192.168.11.1

  #安装了monitor的监测站的基本信息
  monitor_facility_id: 51010001110001
  monitor_facility_ip: 192.168.11.135
  mfname_monitor: monitor监测站